Repository AetherStation/AetherStation13, pull requests merged in 2022-08, with the labels that each got.

#87 Mainframes: or why the fuck did I write a MOS 6502 emulator in BYOND.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/wires.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/processing/mainframe.dm
  code/datums/wires/mainframe.dm
  code/modules/mainframe/instruction_reference.dm
  code/modules/mainframe/linker.dm
  code/modules/mainframe/mainframe.dm
  code/modules/mainframe/manual.dm
  code/modules/mainframe/peripherals.dm
  code/modules/mainframe/processor/6502.dm
  code/modules/mainframe/processor/inst.dm
  code/modules/mainframe/processor/memory_map.dm
  code/modules/mainframe/read_only_memory.dm
  code/modules/mainframe/removable_storage.dm
  icons/obj/machines/mainframe.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/MainframeLibrary.js
  tgui/packages/tgui/interfaces/MainframeLinker.js
  tgui/packages/tgui/interfaces/MainframeMainUnit.js
  tgui/packages/tgui/interfaces/MainframePageEditor.js
  tgui/packages/tgui/interfaces/MainframeRomUnit.js
  tgui/packages/tgui/interfaces/MainframeTerminal.js
Labels: Feature

#119 Resprites ID cards & chip
  code/game/objects/items/card_access_chips.dm
  code/game/objects/items/cards_ids.dm
  icons/mob/clothing/id.dmi
  icons/mob/clothing/id_card.dmi
  icons/obj/card.dmi
  icons/obj/new_id.dmi
Labels: Stale

#134 Re-add PubbyStation
  _maps/_basemap.dm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/pubbystation.json
  code/modules/jobs/card_accesses/station.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/medical_wall.dm
  config/maps.txt
Labels: Mapping

#143 Adjusts buckshot and slug damage.
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance

#144 Fix some away IDs and make AA-chip programmer work with templates properly
  code/controllers/subsystem/id_access.dm
  code/game/objects/items/cards_ids.dm
Labels: Bugfix

#151 Reverting /tg/'s bulky guns, or at least the ones I know of.
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/special/blastcannon.dm
Labels: Balance

#147 remove abundant airlocks from maintbay
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#149 Meta atmos fix
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#146 add silver to chem assembler and synthesizer
  code/modules/plumbing/plumbers/synthesizer.dm
  code/modules/reagents/chemistry/machinery/chem_assembler/chem_assembler.dm
Labels: Balance

#145 Emag message on emagging book inventory management console
  code/modules/library/lib_machines.dm
Labels: Bugfix

#138 Adds suds to using soap, soapy water, temporary decal framework
  code/game/objects/effects/decals/temporary.dm
  code/game/objects/effects/decals/temporary/suds.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/mop.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/mop_bucket.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/effects/suds.dmi
  tgstation.dme
Labels: Feature, Sprites, Bugfix

#156 Added Ammonium Nitrate (ANFO)
  code/modules/cargo/bounties/reagent.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Feature

#161 Prevents the recycler from eating its own parts when dismantled
  code/game/machinery/recycler.dm
Labels: Bugfix

#159 Crashedship TEG and shuttle windows
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
Labels: Mapping

#162 Syndicate Lavaland Polish
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Mapping

#204 Buffing Nuke Op Combat Medic Kit.
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Stale

#140 Deathmatch changes
  _maps/map_files/DM/OSHA_Violator.dmm
  _maps/map_files/DM/SecuRing.dmm
  _maps/map_files/DM/The_Brig.dmm
  _maps/map_files/DM/mech_madness.dmm
  _maps/map_files/DM/ragecage.dmm
  _maps/map_files/DM/shooting_range.dmm
  code/_onclick/hud/ghost.dm
  code/datums/components/material_container.dm
  code/modules/deathmatch/deathmatch_controller.dm
  code/modules/deathmatch/deathmatch_loadouts.dm
  code/modules/deathmatch/deathmatch_lobby.dm
  code/modules/deathmatch/deathmatch_maps.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/power/rtg.dm
Labels: Mapping, Bugfix, Stale

#200 makes possible to connect stasis beds to operating computers again
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/stasis.dm
  code/modules/surgery/surgery.dm
Labels: Stale

#203 Adds honksquad ERT
  code/datums/ert.dm
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Stale
